config/routes.rb
Quiz1::Application.routes.draw do
  root 'words#index'
  
  resources :words

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	def index
		@word = Word.order("RANDOM()").first
	end

	def new
		@word = Word.new
	end 

	def create
		Word.create(word_params)
		redirect_to root_path
	end	

	private

	def word_params
		params.require(:word).permit(:advice, :author)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quiz1</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="box">
<h1><%= @word.advice%></h1>
<p><%= @word.author%></p>
</div>
<div class="links">
<span><%= link_to 'Home ', root_path %></span>
<%= link_to ' Write', new_word_path %>

</div>

<%= yield %>


</body>
</html>

app/views/words/new.html.erb
<div class="box">
<h1>Say something cool</h1>

<%= simple_form_for @word do |f| %>
  <%= f.input :advice %>
  <br />
  <%= f.input :author %>
  <br />
  <%= f.submit 'done!'%>
<% end %>
</div>